jobs:
  test:
    executor:
      name: node/default
      # tag: '12'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests via yarn
version: 2.1
orbs:
  node: circleci/node@4.0.0

workflows:
  node-tests:
    jobs:
      - test
