version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
        command: yarn test
        name: Run tests via yarn
workflows:
  node-tests:
    jobs:
      - test
